sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  

matrix:
  include:

  - ghc: 8.4.3
    env: GHCVER='8.4.3' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.3
        - cabal-install-head
  
install:
  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - echo $PATH
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks sample-site
script:
  - cabal new-test sample-site


notifications:
  email: false

